name: Tests

on:
  workflow_call:

env:
  UV_NO_SYNC: 1

jobs:
  test:
    name: Test (Python=${{ matrix.python-version }}, Resolution=${{ matrix.resolution-strategy }}, Extra=${{ matrix.extra }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
        resolution-strategy: ["lowest-direct", "highest"]
        extra:
          [
            "no-extra",
            "fastapi",
            "sqlmodel",
            "azure-key-vault",
            "aws-secrets-manager",
          ]
    env:
      COVERAGE_FILE: .coverage.python--${{ matrix.python-version }}.resolution--${{ matrix.resolution-strategy }}.extra--${{ matrix.extra }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          version-file: pyproject.toml
          resolution-strategy: lowest
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        run: |
          uv sync \
          --resolution ${{ matrix.resolution-strategy }} \
          ${{ matrix.extra != 'no-extra' && format('--extra {0}', matrix.extra) || '' }}
        shell: bash

      - name: Test
        run: uv run -- pytest --cov=wirio --cov-branch tests
        shell: bash

      - name: Upload coverage artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ env.COVERAGE_FILE }}
          path: ${{ env.COVERAGE_FILE }}
          include-hidden-files: true
          if-no-files-found: error

  publish-coverage:
    name: Publish coverage
    needs: test
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Allow Coveralls to comment on the PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          version-file: pyproject.toml
          resolution-strategy: lowest

      - name: Install Python packages
        run: uv sync --locked
        shell: bash

      - name: Download coverage artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: coverage
          merge-multiple: true

      - name: Combine coverage
        run: uv run -- coverage combine coverage
        shell: bash

      - name: Convert coverage to XML
        run: uv run -- coverage xml --data-file=.coverage -o coverage.xml
        shell: bash

      - name: Publish coverage
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/coverage.xml
